name: Documentation

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: macos-11
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build docs
        run: xcodebuild docbuild -scheme "Decoded" -destination 'platform=macOS,arch=x86_64' -derivedDataPath DerivedData
      - name: Push to documentation repository
        uses: cpina/github-action-push-to-another-repository@v1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: DerivedData/Build/Products/Debug/Decoded.doccarchive
          destination-github-username: siemensikkema
          destination-repository-name: Decoded.docc
          user-email: siemensikkema@users.noreply.github.com
          target-directory: documentation.doccarchive